accounts/urls.py
from django.urls import path

from . import views

from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUpView.as_view(), name='signup'),

    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_succes'),

    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

]

photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('post/', views.CreatePhotoView.as_view(), name='post'),

    path('post_done/', views.PostSuccessView.as_view(), name='post_done'),
    
    path('photos/<int:category>', views.CategoryView.as_view(), name='photos_cat'),

    path('user-list/<int:user>', views.UserView.as_view(), name = 'user_list'),

    path('photo-detail/<int:pk>', views.DetailView.as_view(), name = 'photo_detail'),

    path('mypage/', views.MypageView.as_view(), name = 'mypage'),

     path('photo/<int:pk>/delete', views.PhotoDeleteView.as_view(), name = 'photo_delete'),
]

photoproject/urls.py
from django.contrib import admin
from django.urls import path, include # include追加
# auth.viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # photo.urlsへのURLパターン
    path('', include('photo.urls')),
    
    # accounts.urlsへのURLパターン
    path('', include('accounts.urls')),
    
    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
           template_name = "password_reset.html"),
         name ='password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
           template_name = "password_reset_sent.html"),
         name ='password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
           template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
           template_name = "password_reset_done.html"),
         name ='password_reset_complete'),
]


urlpatterns += static(

    settings.MEDIA_URL,
    
    document_root=settings.MEDIA_ROOT
)

photo/models.py
from django.db import models
# accountsアプリのmodelsモジュールからCustomUserをインポート
from accounts.models import CustomUser

class Category(models.Model):
    '''投稿する写真のカテゴリを管理するモデル
    '''
    # カテゴリ名のフィールド
    title = models.CharField(
        verbose_name='カテゴリ', # フィールドのタイトル
        max_length=20)
    
    def __str__(self):
        '''オブジェクトを文字列に変換して返す
        
        Returns(str):カテゴリ名
        '''
        return self.title

class PhotoPost(models.Model):
    '''投稿されたデータを管理するモデル
    '''
    # CustomUserモデル(のuser_id)とPhotoPostモデルを
    # 1対多の関係で結び付ける
    # CustomUserが親でPhotoPostが子の関係となる
    user = models.ForeignKey(
        CustomUser,
        # フィールドのタイトル
        verbose_name='ユーザー',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
        )
    # Categoryモデル(のtitle)とPhotoPostモデルを
    # 1対多の関係で結び付ける
    # Categoryが親でPhotoPostが子の関係となる
    category = models.ForeignKey(
        Category,
        # フィールドのタイトル
        verbose_name='カテゴリ',
        # カテゴリに関連付けられた投稿データが存在する場合は
        # そのカテゴリを削除できないようにする
        on_delete=models.PROTECT
        )
    # タイトル用のフィールド
    title = models.CharField(
        verbose_name='タイトル', # フィールドのタイトル
        max_length=200        # 最大文字数は200
        )
    # コメント用のフィールド
    comment = models.TextField(
        verbose_name='コメント',  # フィールドのタイトル
        )
    # イメージのフィールド1
    image1 = models.ImageField(
        verbose_name='イメージ1',# フィールドのタイトル
        upload_to = 'photos'   # MEDIA_ROOT以下のphotosにファイルを保存  
        )
    # イメージのフィールド2
    image2 = models.ImageField(
        verbose_name='イメージ2',# フィールドのタイトル
        upload_to = 'photos',  # MEDIA_ROOT以下のphotosにファイルを保存
        blank=True,            # フィールド値の設定は必須でない
        null=True              # データベースにnullが保存されることを許容
        )
    # 投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name='投稿日時', # フィールドのタイトル
        auto_now_add=True       # 日時を自動追加
        )
    
    def __str__(self):
        '''オブジェクトを文字列に変換して返す
        
        Returns(str):投稿記事のタイトル
        '''
        return self.title

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
    '''ModelFormのサブクラス
    '''
    class Meta:
        '''ModelFormのインナークラス
        
        Attributes:
          model: モデルのクラス
          fields: フォームで使用するモデルのフィールドを指定
        '''
        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2']

photo/views.py
from django.shortcuts import render
# django.views.genericからTemplateView、ListViewをインポート
from django.views.generic import TemplateView, ListView
# django.views.genericからCreateViewをインポート
from django.views.generic import CreateView
# django.urlsからreverse_lazyをインポート
from django.urls import reverse_lazy
# formsモジュールからPhotoPostFormをインポート
from .forms import PhotoPostForm
# method_decoratorをインポート
from django.utils.decorators import method_decorator
# login_requiredをインポート
from django.contrib.auth.decorators import login_required
# modelsモジュールからモデルPhotoPostをインポート
from .models import PhotoPost
# django.views.genericからDetailViewをインポート
from django.views.generic import DetailView

from django.views.generic import DeleteView

class IndexView(ListView):
    '''トップページのビュー
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # モデルBlogPostのオブジェクトにorder_by()を適用して
    # 投稿日時の降順で並べ替える
    queryset = PhotoPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 9

# デコレーターにより、CreatePhotoViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    '''写真投稿ページのビュー
    
    PhotoPostFormで定義されているモデルとフィールドと連携して
    投稿データをデータベースに登録する
    
    Attributes:
      form_class: モデルとフィールドが登録されたフォームクラス
      template_name: レンダリングするテンプレート
      success_url: データベスへの登録完了後のリダイレクト先
    '''
    # forms.pyのPhotoPostFormをフォームクラスとして登録
    form_class = PhotoPostForm
    # レンダリングするテンプレート
    template_name = "post_photo.html"
    # フォームデータ登録完了後のリダイレクト先
    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録をここで行う
        
        parameters:
          form(django.forms.Form):
            form_classに格納されているPhotoPostFormオブジェクト
        Return:
          HttpResponseRedirectオブジェクト:
            スーパークラスのform_valid()の戻り値を返すことで、
            success_urlで設定されているURLにリダイレクトさせる
        '''
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    '''投稿完了ページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
    '''
    # index.htmlをレンダリングする
    template_name ='post_success.html'

class CategoryView(ListView):
    '''カテゴリページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9

    def get_queryset(self):
      '''クエリを実行する
      
      self.kwargsの取得が必要なため、クラス変数querysetではなく、
      get_queryset（）のオーバーライドによりクエリを実行する
      
      Returns:
        クエリによって取得されたレコード
      '''     
      # self.kwargsでキーワードの辞書を取得し、
      # categoryキーの値(Categorysテーブルのid)を取得
      category_id = self.kwargs['category']
      # filter(フィールド名=id)で絞り込む
      categories = PhotoPost.objects.filter(
        category=category_id).order_by('-posted_at')
      # クエリによって取得されたレコードを返す
      return categories

class UserView(ListView):
    '''ユーザーの投稿一覧ページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9

    def get_queryset(self):
      '''クエリを実行する
      
      self.kwargsの取得が必要なため、クラス変数querysetではなく、
      get_queryset（）のオーバーライドによりクエリを実行する
      
      Returns:
        クエリによって取得されたレコード
      '''
      # self.kwargsでキーワードの辞書を取得し、
      # userキーの値(ユーザーテーブルのid)を取得
      user_id = self.kwargs['user']
      # filter(フィールド名=id)で絞り込む
      user_list = PhotoPost.objects.filter(
        user=user_id).order_by('-posted_at')
      # クエリによって取得されたレコードを返す
      return user_list

class DetailView(DetailView):
    '''詳細ページのビュー
    
    投稿記事の詳細を表示するのでDetailViewを継承する
     Attributes:
      template_name: レンダリングするテンプレート
      model: モデルのクラス
    '''
    # post.htmlをレンダリングする
    template_name ='detail.html'
    # クラス変数modelにモデルBlogPostを設定
    model = PhotoPost

class MypageView(ListView):
    
    template_name = 'mypage.html'

    paginate_by = 9

    def get_queryset(self):
        
      queryset = PhotoPost.objects.filter(
         user=self.request.user) .order_by('-posted_at')
      
      return queryset
    
class PhotoDeleteView(DeleteView):
   
   model = PhotoPost

   template_name = 'photo_delete.html'

   success_url = reverse_lazy('photo:mypage')

   def delete(self, request, *args, **kwargs):
      
    return super().delete(request, *args, **kwargs)

photo/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする-->
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>    
  </head>
  
  <body>
    <!-- ページのヘッダー-->
    <header>
      <!-- ナビゲーションバーのヘッダー-->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <!-- ヘッダーのタイトルと本文-->
              <h4 class="text-white">お気に入りを見つけよう！</h4>
              <p class="text-muted">
                誰でも参加できる写真投稿サイトです。
                自分で撮影した写真なら何でもオッケー！
                でも、カテゴリに属する写真に限ります。
                コメントも付けてください！
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー-->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー-->
                <li><a href="{% url 'photo:mypage' %}"
                       class="text-white">マイページ</a></li>
              <li>
                <form action="{% url 'accounts:logout' %}" method="post">
                     {% csrf_token %}
                     <button class="btn-link text-white p-0" type="submit" style="border: none; background:inherit">ログアウト</button>
                </form>
              </li>
                <li><a href="{% url 'password_reset' %}"
                       class="text-white">パスワードのリセット</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー-->
                <li><a href="{% url 'accounts:signup' %}"
                       class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}"
                       class="text-white">ログイン</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- ナビゲーションバー-->
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <!-- トップページへのリンク-->
          <a href="{% url 'photo:index' %}"
             class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="20" height="20" fill="none"
                 stroke="currentColor"
                 stroke-linecap="round"
                 stroke-linejoin="round"
                 stroke-width="2"
                 aria-hidden="true"
                 class="me-2"
                 viewBox="0 0 24 24">
                 <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                 <circle cx="12" cy="13" r="4"/></svg>
            <!-- リンクテキスト-->
            <strong>Photo Gallery</strong>
          </a>
          <!-- トグルボタン-->
          <button class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarHeader"
                  aria-controls="navbarHeader"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    
    <!-- メインコンテンツ-->
    <main>
      <!-- <main>タグの要素をすべて削除して以下に書き換え-->
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む-->
      {% block contents %}{% endblock %}
    </main>
    
    <!-- フッター -->
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え-->
        <p class="mb-1">
          Photo Gallery is &copy; Bootstrap, but please post a lot!</p>
      </div>
    </footer>
    
    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>      
  </body>
</html>

photo/templates/detail.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Photo Detail{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム-->
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる-->
          <div class="col offset-3">
            <!-- タイトル -->
            <h2>{{object.title}}</h2>
            <!-- コメント -->
            <p>{{object.comment}}</p>
            <br>
            <!-- 投稿日時 -->
            <p>{{object.posted_at}}に投稿</p>
            <!-- 1枚目の写真 -->
            <p><img src="{{ object.image1.url }}"></img></p>
            <!-- 2枚目の写真が投稿されていたら表示する-->
            {% if object.image2 %}
              <p><img src="{{ object.image2.url }}"></img></p>
            {% endif %}
            
            <!-- 投稿写真がログイン中のユーザーのものであれば削除ボタンを表示-->
            {% if request.user == object.user %}
            <form method="POST">
            <!-- リンク先のURL
                 photo/<Photo postsテーブルのid値>/delete/-->
            <a href="{% url 'photo:photo_delete' object.pk %}"
               class="btn btn-primary my-2">削除する</a>
            {% endif %}
            
          </dv>
        </dv>
      </dv>
      {% endblock %}

photo/templates/index.html
{% extends 'base.html' %}
{% block title %}Photo Gallery{% endblock %}

    {% block contents %}

    {% include "photos_title.html" %}

    {% include "photos_list.html" %}

    {% endblock %}

photo/templates/mypage.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Mypage{% endblock %}

      {% block contents %}
      
      <!-- タイトルテンプレートは組み込まない-->
      
      <!-- ユーザーの投稿件数を表示-->
      {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
          <h4>{{user.username}}さんのマイページ</h4>
          {% if object_list.count == 0 %}
            <p>{{user.username}}さんの投稿はありません</p>
          {% else %}
            <p>投稿<strong>{{object_list.count}}</strong>件</p>
          {% endif %}
          <a href="{% url 'photo:post' %}">投稿する</a>
        </div>
        <hr>
      {% endif %}
      
      <!-- 投稿一覧テンプレートの組み込み-->
      {% include "photos_list.html" %}
        
      <!-- ページネーションの組み込み-->
      {% include "pagination.html" %}

      {% endblock %}

photo/templates/pagination.html
<!-- ページネーションのアイコンを左右中央に配置 -->
<ul class="pagination"
    style="justify-content:center">
    <!--
    前ページを表示するアイコンとリンクの設定
    ページネーションされたPageオブジェクトをorderby_recordsで取得
    Page.has_previous: 直前にページがある場合にTrueを返す
    -->
    {% if page_obj.has_previous %}
    <!--
    前のページが存在する場合はそのページへのリンクが設定されたアイコン[<<]を表示
    Page.previous_page_number: 直前のページ番号を返す
    -->
    <li class="page-item">
        <a class="page-link"
        　　 href="?page={{ page_obj.previous_page_number }}"
        　　 aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    <!--
     すべてのページについてページ番号のアイコンを表示
     paginator.page_range: [1, 2, 3, 4] のように1から始まるページ番号を返す
     page_obj.paginator.page_rangeとして取得
     ブロックパラメーターnumに順次取り出される
    -->
    {% for num in page_obj.paginator.page_range %}
        <!--
        各ページのアイコンを出力
        Page.number: 引き渡されたページのページ番号を返す
        -->
        {% if page_obj.number == num %}
        <!--
        処理中のページ番号が引き渡されたページのページ番号と一致する場合は
        ページ番号のアイコン(アクティブ状態)を表示(リンクは設定しない)
        -->
        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>
        <!--
        ページ番号が引き渡されたページのページ番号と一致しない場合
        -->
        {% else %}
        <!--
        ページ番号のアイコン(アクティブ状態ではない)にリンクを設定して表示
        -->
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}
    <!--
    次ページへのリンクを示すアイコンの表示
    Page.has_next: 次のページがある場合にTrueを返す
    -->
    {% if page_obj.has_next %}
    <!--
    次ページが存在する場合はリンクを設定したアイコン［>>]を表示
    Page.next_page_number: 次のページ番号を返す
    -->
    <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.next_page_number }}"
           aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

photo/templates/photo_delete.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Photo Detail{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる -->
          <div class="col offset-3">
            <form method="POST">
              <br>
              <p>削除してもいいですか?</p>
              {% csrf_token %}
              <button class="btn btn-primary my-2"
                      type="submit">削除</button>
              <a href="{% url 'photo:photo_detail' object.pk %}"
                 class="btn btn-secondary my-2">キャンセル</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

photo/templates/photos_list.html
  <div class="album py-5 bg-light">
    <!-- Bootstrapのグリッドシステムを適用 -->
    <div class="container">
      <!-- 行要素を配置 -->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <!-- レコードが格納されたobject_listから
             レコードを1行ずつrecordに取り出す-->
        {% for record in object_list %}
        <!-- 列要素を配置 -->
        <div class="col">
          <div class="card shadow-sm">
            <!-- svgタグをimgに変更
                 src属性を追加して1枚目のイメージのURLを設定 -->
            <img src="{{ record.image1.url }}"
                 class="bd-placeholder-img card-img-top"
                 width="100%" height="225"
                 xmlns="http://www.w3.org/2000/svg"
                 role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice"
                 focusable="false">
                 <title>Placeholder</title>
                 <rect width="100%" height="100%" fill="#55595c"/>
                 <!-- <text>～</text>を削除-->
            </img>
            <!-- タイトルとボタンを出力するブロック -->
            <div class="card-body">
              <p class="card-text">
                <!-- titleフィールドを出力 -->
                {{record.title}}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <!-- 詳細ページを表示するボタン -->
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
                          onclick="location.href='{% url 'photo:photo_detail' record.pk %}'">
                          View</button>
                  <!-- カテゴリを表示するボタン -->
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
                          onclick="location.href='{% url 'photo:photos_cat' category=record.category.id %}'">
                          {{record.category.title}}</button>
                </div>
                <!-- 投稿したユーザー名を出力-->
               <a href="{% url 'photo:user_list' user=record.user.id %}">
                <small class="text-muted">
                  {{record.user.username}}</small>
               </a> 
              </div>
            </div>
          </div>
        <!-- 列要素ここまで -->
        </div>
        <!-- forブロック終了 -->
        {% endfor %}
      <!-- 行要素ここまで -->
      </div>
    <!-- グリッドシステムここまで -->
    </div>
  </div>

photo/templates/photos_title.html
  <!-- タイトルとナビゲーションボタン -->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <!-- タイトルと本文 -->
        <h1 class="fw-light">Photo Gallery</h1>
        <p class="lead text-muted">
          コメントを見て写真に描かれた世界に思いを馳せましょう。
          素敵な写真とコメントをお待ちしています!</p>
        <div class="d-flex justify-content-center gap-2">
          <!-- ナビゲーションボタン -->
          {% if user.is_authenticated %}
          <!-- ログイン中のボタン -->
          <a href="{% url 'photo:post' %}"
             class="btn btn-primary my-2">投稿する</a>
          <!-- <a href="{% url 'accounts:logout' %}"class="btn btn-secondary my-2">ログアウト</a> -->
           <form action="{% url 'accounts:logout' %}" method="post">
                     {% csrf_token %}
                     <button class="btn btn-secondary my-2" type="submit">ログアウト</button>
                </form>
          {% else %}
          <!-- ログイン状態ではない場合のボタン -->
          <a href="{% url 'accounts:signup' %}"
             class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}"
             class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>

photo/templates/post_photo.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Post{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる -->
          <div class="col offset-2">
            <!-- ファイルをアップロードする場合は
                 enctype="multipart/form-data"が必要 -->
            <form method="POST"
                  enctype="multipart/form-data">
              {% csrf_token %}
              <table>
                <tr>
                  <th>カテゴリ</th>
                  <td>{{ form.category }}</td>
                </tr>
                <tr>
                  <th>タイトル</th>
                  <td>{{ form.title }}</td>
                </tr>
                <tr>
                  <th>コメント</th>
                  <td>{{ form.comment }}</td>
                </tr>
                <tr>
                  <th>画像1</th>
                  <td>{{ form.image1 }}</td>
                </tr>
                <tr>
                  <th>画像2</th>
                  <td>{{ form.image2 }}</td>
                </tr>
              </table>
              <hr>
              <button type="submit">投稿する</button>
            </form>        
          </dv>
        </dv>
      </dv>
      {% endblock %}

photo/templates/post_success.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}

<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Post Success{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br><br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる -->
          <div class="col offset-2">
            <h4>投稿が完了しました!</h4>  
          </dv>
        </dv>
      </dv>
      {% endblock %}